export const testStargrams = [
  {
    sender: 'Maria Lopez',
    recipient: 'Jake Thompson',
    show: 'Fri, Mar 20 - 7pm',
    treat: 'Chocolate candy',
    message: 'Break a leg tonight! So proud of you!',
    allergies: 'no',
  },
  {
    sender: 'David Chen',
    recipient: 'Sophie Williams',
    show: 'Fri, Mar 20 - 7pm',
    treat: 'Gummy bears',
    message: 'You are going to be amazing up there. We love you!',
    allergies: 'Peanuts',
  },
  {
    sender: 'Grandma Rose',
    recipient: 'Ethan Park',
    show: 'Sat, Mar 21 - 2pm',
    treat: 'Lollipop',
    message: 'My little star! Grandma is watching from the front row!',
    allergies: 'no',
  },
  {
    sender: 'The Nguyen Family',
    recipient: 'Lily Nguyen',
    show: 'Sat, Mar 21 - 2pm',
    treat: 'Chocolate candy',
    message: 'We are all here cheering for you. Shine bright!',
    allergies: 'Dairy',
  },
  {
    sender: 'Coach Martinez',
    recipient: 'Whole Cast',
    show: 'Sat, Mar 21 - 7pm',
    treat: 'Gummy bears',
    message: 'What an incredible group of performers. Enjoy every moment!',
    allergies: 'no',
  },
  {
    sender: 'Auntie Kim',
    recipient: 'Mia Johnson',
    show: 'Sat, Mar 21 - 7pm',
    treat: 'Sour candy',
    message: 'You were born to be on that stage!',
    allergies: 'no',
  },
  {
    sender: 'Tyler Brooks',
    recipient: 'Hannah Brooks',
    show: 'Fri, Mar 20 - 7pm',
    treat: 'Chocolate candy',
    message: 'Best sister ever. Knock em dead!',
    allergies: 'Tree nuts',
  },
  {
    sender: 'Mr. and Mrs. Davis',
    recipient: 'Oliver Davis',
    show: 'Sat, Mar 21 - 2pm',
    treat: 'Lollipop',
    message: 'So proud of all your hard work this semester.',
    allergies: 'no',
  },
  {
    sender: 'Jess',
    recipient: 'Chloe Ramirez',
    show: 'Fri, Mar 20 - 7pm',
    treat: 'Gummy bears',
    message: 'Best friends forever. You are a STAR!!!!',
    allergies: 'no',
  },
  {
    sender: 'The Patel Family',
    recipient: 'Arjun Patel',
    show: 'Sat, Mar 21 - 7pm',
    treat: 'Chocolate candy',
    message: 'We drove four hours to see you perform and it is worth every mile.',
    allergies: 'Gluten',
  },
  {
    sender: 'Mom',
    recipient: 'Emma Sutton',
    show: 'Sat, Mar 21 - 2pm',
    treat: 'Sour candy',
    message: 'My sweet girl, you make me proud every single day.',
    allergies: 'no',
  },
  {
    sender: 'Uncle Steve',
    recipient: 'Noah Garcia',
    show: 'Fri, Mar 20 - 7pm',
    treat: 'Chocolate candy',
    message: 'From one performer to another — own that stage!',
    allergies: 'no',
  },
  {
    sender: 'Sarah and Ben',
    recipient: 'Zoe Mitchell',
    show: 'Sat, Mar 21 - 7pm',
    treat: 'Lollipop',
    message: 'We cannot wait to see you shine tonight!',
    allergies: 'Soy',
  },
  {
    sender: 'Dad',
    recipient: 'Lucas Kim',
    show: 'Sat, Mar 21 - 2pm',
    treat: 'Gummy bears',
    message: 'Remember: have fun up there. That is what it is all about.',
    allergies: 'no',
  },
];
